const express = require('express')
const app = express()
require('dotenv').config()
app.use(express.json())
const database = require('./Db/Connection')
const heroRoute = require('./Hero/Hero.route')
const aboutRoute = require('./About/About.route')
app.use(heroRoute)
app.use(aboutRoute)
app.listen(8080, () => console.log('listen to port 8080'))
